# config file for travis
language: python
python:
  - "2.7"
  - "3.6"

before_script:
  - psql -c 'create database jenkinsDev;' -U postgres
  - pip install -r requirements.txt

script:
  - cd Server
  - python manage.py makemigrations
  - python manage.py migrate
  - export DJANGO_SETTINGS_MODULE=jenkinsServer.settings
  - python -m pytest tests
  # - pylint Server