# config file for travis
language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest

before-install:
  - pip install psycopg2-binary
  - pip install pylint
  - psql -c 'create database jenkinsDev;' -U postgres
scripts:
  - cd Server
  - python manage.py migrate
  - python add_database_data.py
  - python -m pytest tests
  - pylint Server.py