# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 10:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandWord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('word', models.CharField(default='none', max_length=30)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('word_action', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
