# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='body',
            new_name='username',
        ),
    ]
