# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20180920_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='address',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
