# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 13:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='body',
        ),
        migrations.AddField(
            model_name='answer',
            name='address',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
